// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lechuhuuha/oneshield/pkg/config"
	"github.com/lechuhuuha/oneshield/transports/http"
)

// Injectors from wire.go:

func NewService(cfg *config.Config) (*App, func(), error) {
	server := http.NewServer(cfg)
	app := NewApp(server)
	return app, func() {
	}, nil
}
